// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZXyz-KT00YoTFGsgrCDjffFFn-nja8g',
    appId: '1:911440490125:web:dcf310fd4828d97d043cc4',
    messagingSenderId: '911440490125',
    projectId: 'flutter-project-e2ab0',
    authDomain: 'flutter-project-e2ab0.firebaseapp.com',
    storageBucket: 'flutter-project-e2ab0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqpy9yTnCUq9nzwjapsx8Z2rjd-jkhL-w',
    appId: '1:911440490125:android:f1444fddf0317a6d043cc4',
    messagingSenderId: '911440490125',
    projectId: 'flutter-project-e2ab0',
    storageBucket: 'flutter-project-e2ab0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJfu6-YqaYtf8jkn84Wm_b3nB3HnLonMY',
    appId: '1:911440490125:ios:e0a48bf0fc05956f043cc4',
    messagingSenderId: '911440490125',
    projectId: 'flutter-project-e2ab0',
    storageBucket: 'flutter-project-e2ab0.firebasestorage.app',
    iosBundleId: 'com.alvarocori.flutterPush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJfu6-YqaYtf8jkn84Wm_b3nB3HnLonMY',
    appId: '1:911440490125:ios:e0a48bf0fc05956f043cc4',
    messagingSenderId: '911440490125',
    projectId: 'flutter-project-e2ab0',
    storageBucket: 'flutter-project-e2ab0.firebasestorage.app',
    iosBundleId: 'com.alvarocori.flutterPush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZXyz-KT00YoTFGsgrCDjffFFn-nja8g',
    appId: '1:911440490125:web:3bd5c03d260f6886043cc4',
    messagingSenderId: '911440490125',
    projectId: 'flutter-project-e2ab0',
    authDomain: 'flutter-project-e2ab0.firebaseapp.com',
    storageBucket: 'flutter-project-e2ab0.firebasestorage.app',
  );
}
